source: src
paths:
  uploads: uploads
  static: ''
  collections: ''
  data: ''
  layouts:
collections_config:
  pages:
    path: pages
    output: false
    url:
    filter:
    parse_branch_index:
    name:
    description: ''
    icon: notes
    documentation:
    preview:
    sort:
    sort_options:
    singular_name:
    singular_key:
    _editables:
    _inputs:
    _select_data:
    _structures:
    add_options:
    create:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url:
    schemas:
    schema_key:
timezone: Etc/UTC
_editables:
  snippet: true
_snippets_imports:
  mdx: true
_snippets:
  nxt_hint:
    template: mdx_paired_component
    inline: true
    preview:
      text: NXT Hint
    definitions:
      component_name: nxt_hint
      content_key: hint_text
      named_args:
        - editor_key: tooltip
          source_key: tooltip
          type: string
    _inputs:
      tooltip:
        type: text
      hint_text:
        comment: A comment
