source: src
paths:
  uploads: uploads
  static: public
  collections: ''
  data: ''
  layouts:
collections_config:
  pages:
    path: pages
    output: false
    url:
    filter:
    parse_branch_index:
    name:
    description: ''
    icon: notes
    documentation:
    preview:
    sort:
    sort_options:
    singular_name:
    singular_key:
    _editables:
    _inputs:
    _select_data:
    _structures:
    add_options:
    create:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url:
    schemas:
      default:
        name: New Page
        path: schemas/page.mdx
timezone: Etc/UTC
_editables:
  content:
    blockquote: true
    bold: true
    format: p h1 h2 h3 h4 h5 h6
    italic: true
    strike: true
    subscript: true
    superscript: true
    underline: true
    link: true
    bulletedlist: true
    indent: true
    numberedlist: true
    outdent: true
    code: true
    snippet: true
_snippets_imports:
  mdx: true
_snippets:
  nxt_hint:
    template: mdx_component
    inline: true
    preview:
      text: NXT Hint
    definitions:
      component_name: NXT_Hint
      named_args:
        - editor_key: tooltip
          source_key: tooltip
          type: string
        - editor_key: display_text
          source_key: display_text
          type: string
    _inputs:
      tooltip:
        type: text
        comment: The tooltip text that should show on hover
      display_text:
        type: text
        comment: What text you want to display in the text
  
  code_block:
    template: mdx_paired_component
    inline: false
    preview:
      text: Code Block
    definitions:
      component_name: Code_Block
      content_key: content
    _inputs:
      content:
        type: markdown
        comment: The content of this code block
  
  test_component:
    snippet: "<Code_Block content={`[[inner]]`} hints={[[hints]]} />"
    params:
      inner:
        parser: content
        options:  
          editor_key: inner_code
          style:
            output: block
            block:
              indent: ""
      hints:
        parser: key_values
        options:
          editor_key: hints
    inline: false
    preview:
      icon: code
      text:
        - key: content
        - 'Code Block'
    _inputs:
      inner_code:
        type: code
      hints:
        type: array
        options:
          structures: _structures.hint
    _structures:
      hint:
        values:
          - value:
              display_text: ""
              tooltip: ""

        
        #- editor_key: hints
        #  source_key: hints
        #  type: array